#!/bin/bash
#SBATCH --job-name=wes_job_1          # Job Name
#SBATCH --mail-type=END,FAIL          # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=jtk622@gmail.com  # Where to send mail	
#SBATCH --ntasks=1                    # Run on a single CPU
#SBATCH --cpus-per-task=16            # CPUs per task
#SBATCH --mem=120gb                   # Job memory request
#SBATCH --qos=group-b                 # Use burst capacity when available
#SBATCH --time=72:00:00               # Time limit hrs:min:sec
#SBATCH --output=serial_test_%j.log   # Standard output and error log
pwd; hostname; date

module load ufrc
module load nextflow/0.32.0
module load singularity/2.5.2
 
echo "Running nextflow script on HiPerGator"
 
nextflow run <nextflow_script> -profile ufrcSlurm
 
date
